### ISSUE TITLE
Aborted (core dumped)  corrupted size vs. prev_size

### ISSUE THREAD

**Issue by arckalsun** [guanzhi/GmSSL#1061]
**Describe the bug**
```shell
root@42c3a0cd2c15:~# python -c "import requests; resp=requests.get('https://static.pddpic.com/assets/js/dba_a6f5600ee6b41a489053_1026.js'); print(resp.status_code)"
free(): invalid pointer
Aborted (core dumped)
root@42c3a0cd2c15:~#
```
test url: https://static.pddpic.com/assets/js/dba_a6f5600ee6b41a489053_1026.js
**Expected behavior**
 
**Screenshots**
 
![image](https://user-images.githubusercontent.com/19990356/105676182-1bd05980-5f25-11eb-9123-53344d2d1b29.png)

**Environments**
- OS:  docker
```
> root@42c3a0cd2c15:~# lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 10 (buster)
    Release:	10
    Codename:	buster
- Python 3.6.12
- requests==2.25.1
```
- Compiler: 
```
- root@42c3a0cd2c15:~# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
root@42c3a0cd2c15:~# 
```
**Additional context**
how to resolve it?

**Comment by arckalsun** [comment]
gdb debug:
```
root@42c3a0cd2c15:~# gdb /usr/local/bin/python core_python_11449 
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/python...done.

warning: core file may not match specified executable file.
[New LWP 11449]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python -c import requests; resp=requests.get('https://static.pddpic.com/assets/'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 

```

**Comment by arckalsun** [comment]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd6ac0fa535 in __GI_abort () at abort.c:79
#2  0x00007fd6ac151508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd6ac25c28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fd6ac157c1a in malloc_printerr (str=str@entry=0x7fd6ac25a43b "free(): invalid pointer") at malloc.c:5341
#4  0x00007fd6ac15942c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x00007fd6ab87f63d in asn1_string_embed_free () from /usr/local/lib/libcrypto.so.1.1
#6  0x00007fd6ab8897bf in asn1_primitive_free.localalias () from /usr/local/lib/libcrypto.so.1.1
#7  0x00007fd6ab889ca1 in asn1_template_free () from /usr/local/lib/libcrypto.so.1.1
#8  0x00007fd6ab889fbf in ASN1_item_free () from /usr/local/lib/libcrypto.so.1.1
#9  0x00007fd6aba05de3 in OPENSSL_sk_pop_free () from /usr/local/lib/libcrypto.so.1.1
#10 0x00007fd6aba2062f in x509_name_ex_free () from /usr/local/lib/libcrypto.so.1.1
#11 0x00007fd6ab889d77 in asn1_template_free () from /usr/local/lib/libcrypto.so.1.1
#12 0x00007fd6ab889b9c in asn1_template_free () from /usr/local/lib/libcrypto.so.1.1
#13 0x00007fd6ab889fbf in ASN1_item_free () from /usr/local/lib/libcrypto.so.1.1
#14 0x00007fd6aba14c51 in cleanup () from /usr/local/lib/libcrypto.so.1.1
#15 0x00007fd6aba05de3 in OPENSSL_sk_pop_free () from /usr/local/lib/libcrypto.so.1.1
#16 0x00007fd6aba150b6 in X509_STORE_free () from /usr/local/lib/libcrypto.so.1.1
#17 0x00007fd6abb66460 in SSL_CTX_free () from /usr/local/lib/libssl.so.1.1
#18 0x00007fd6abd98ea9 in context_dealloc (self=0x7fd6aaf7b3c8) at /app/Python-3.6.12/Modules/_ssl.c:2955
#19 0x00005646aa6e8cb0 in subtype_dealloc (self=0x7fd6aaf7b3c8) at Objects/typeobject.c:1222
#20 0x00005646aa6cb2f5 in dict_dealloc (mp=0x7fd6aaf7de58) at Objects/dictobject.c:2017
#21 0x00005646aa6e8c2f in subtype_dealloc (self=0x7fd6aaf7a630) at Objects/typeobject.c:1207
#22 0x00005646aa76d37c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:1308
#23 0x00005646aa7665ac in PyEval_EvalFrameEx (throwflag=0, f=0x5646ac4321a8) at Python/ceval.c:754
#24 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=1, globals=globals@entry=0x7fd6ab3cabd0) at Python/ceval.c:4933
#25 0x00005646aa7678ef in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6ab33fbf8) at Python/ceval.c:4968
#26 call_function (pp_stack=pp_stack@entry=0x7fffc54f08a0, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#27 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#28 0x00005646aa76732a in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaf9f398) at Python/ceval.c:754
#29 _PyEval_EvalCodeWithName (_co=0x7fd6abc43db0, globals=globals@entry=0x7fd6abc5ca20, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kwnames=0x0, kwargs=0x7fd6aaee81f0, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, 
    name=0x7fd6abd4b370, qualname=0x7fd6ab3cd500) at Python/ceval.c:4166
#30 0x00005646aa76761c in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6aaf750d0) at Python/ceval.c:4992
#31 call_function (pp_stack=pp_stack@entry=0x7fffc54f0b40, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#32 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#33 0x00005646aa7665ac in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaee8048) at Python/ceval.c:754
#34 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=1, globals=globals@entry=0x7fd6ab3d0e58) at Python/ceval.c:4933
#35 0x00005646aa7678ef in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6ab392d90) at Python/ceval.c:4968
#36 call_function (pp_stack=pp_stack@entry=0x7fffc54f0cf0, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#37 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#38 0x00005646aa7665ac in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaf9f1f0) at Python/ceval.c:754
#39 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=1, globals=globals@entry=0x7fd6abc5ca20) at Python/ceval.c:4933
#40 0x00005646aa7678ef in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6ab3aed08) at Python/ceval.c:4968
#41 call_function (pp_stack=pp_stack@entry=0x7fffc54f0ea0, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#42 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#43 0x00005646aa7665ac in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaf9ee08) at Python/ceval.c:754
#44 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=1, globals=globals@entry=0x7fd6aaf665e8) at Python/ceval.c:4933
#45 0x00005646aa7678ef in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6aaf63b70) at Python/ceval.c:4968
#46 call_function (pp_stack=pp_stack@entry=0x7fffc54f1050, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#47 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#48 0x00005646aa7665ac in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaf9ec50) at Python/ceval.c:754
#49 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=1, globals=globals@entry=0x7fd6abc40870) at Python/ceval.c:4933
#50 0x00005646aa7678ef in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6aaf77a60) at Python/ceval.c:4968
#51 call_function (pp_stack=pp_stack@entry=0x7fffc54f1200, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#52 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#53 0x00005646aa76732a in PyEval_EvalFrameEx (throwflag=0, f=0x7fd6aaee71f8) at Python/ceval.c:754
#54 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fd6aaf61780, globals=globals@entry=0x7fd6abc40870, locals=locals@entry=0x0, args=args@entry=0x7fffc54f1490, argcount=argcount@entry=4, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, 
    kwdefs=0x0, closure=0x0, name=0x7fd6abf01670, qualname=0x7fd6abc40e88) at Python/ceval.c:4166
#55 0x00005646aa77073c in _PyFunction_FastCallDict (func=func@entry=0x7fd6aaf77378, args=args@entry=0x7fffc54f1490, nargs=nargs@entry=4, kwargs=kwargs@entry=0x0) at Python/ceval.c:5084
--Type <RET> for more, q to quit, c to continue without paging-- 
#56 0x00005646aa686341 in _PyObject_FastCallDict (func=0x7fd6aaf77378, args=0x7fffc54f1490, nargs=4, kwargs=0x0) at Objects/abstract.c:2310
#57 0x00005646aa68656d in _PyObject_Call_Prepend (func=0x7fd6aaf77378, obj=<optimized out>, args=0x7fd6aaf922d0, kwargs=0x0) at Objects/abstract.c:2373
#58 0x00005646aa68629a in _PyObject_FastCallDict (func=0x7fd6abedeac8, args=0x7fffc54f1580, nargs=3, kwargs=0x0) at Objects/abstract.c:2331
#59 0x00005646aa6873b2 in PyObject_CallFunctionObjArgs (callable=callable@entry=0x7fd6abedeac8) at Objects/abstract.c:2827
#60 0x00005646aa76a57f in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3293
#61 0x00005646aa76732a in PyEval_EvalFrameEx (throwflag=0, f=0x5646ac0b1728) at Python/ceval.c:754
#62 _PyEval_EvalCodeWithName (_co=0x7fd6ab13fae0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7fd6abdce9e0, argcount=2, kwnames=kwnames@entry=0x7fd6abdd4c40, kwargs=0x7fd6abdd4c48, kwcount=4, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4166
#63 0x00005646aa7680ee in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7fd6abdce9e0, argcount=<optimized out>, kws=kws@entry=0x7fd6abdd4c40, kwcount=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at Python/ceval.c:4187
#64 0x00005646aa6b0436 in function_call (func=0x7fd6ab149950, arg=0x7fd6abdce9c8, kw=0x7fd6abddc3f0) at Objects/funcobject.c:604
#65 0x00005646aa68610a in PyObject_Call (func=0x7fd6ab149950, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
#66 0x00005646aa76d598 in do_call_core (kwdict=0x7fd6abddc3f0, callargs=0x7fd6abdce9c8, func=0x7fd6ab149950) at Python/ceval.c:5120
#67 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3404
#68 0x00005646aa76732a in PyEval_EvalFrameEx (throwflag=0, f=0x5646ac0bd5a8) at Python/ceval.c:754
#69 _PyEval_EvalCodeWithName (_co=0x7fd6ab14be40, globals=globals@entry=0x7fd6ab2ad678, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kwnames=0x0, kwargs=0x5646ac0d40e0, kwcount=0, kwstep=1, defs=0x7fd6ab2a4418, defcount=1, kwdefs=0x0, 
    closure=0x0, name=0x7fd6abefc490, qualname=0x7fd6abefc490) at Python/ceval.c:4166
#70 0x00005646aa76761c in fast_function (kwnames=0x0, nargs=1, stack=<optimized out>, func=0x7fd6aaf77c80) at Python/ceval.c:4992
#71 call_function (pp_stack=pp_stack@entry=0x7fffc54f1ce0, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4872
#72 0x00005646aa76d671 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#73 0x00005646aa76732a in PyEval_EvalFrameEx (throwflag=0, f=0x5646ac0d3f58) at Python/ceval.c:754
#74 _PyEval_EvalCodeWithName (_co=_co@entry=0x7fd6abe5d9c0, globals=globals@entry=0x0, locals=locals@entry=0x7fd6abea3120, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, 
    closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4166
#75 0x00005646aa768073 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=locals@entry=0x7fd6abea3120, globals=globals@entry=0x0, _co=_co@entry=0x7fd6abe5d9c0) at Python/ceval.c:4187
#76 PyEval_EvalCode (co=co@entry=0x7fd6abe5d9c0, globals=globals@entry=0x7fd6abea3120, locals=locals@entry=0x7fd6abea3120) at Python/ceval.c:731
#77 0x00005646aa66261b in run_mod (arena=0x7fd6abebd198, flags=0x7fffc54f1f5c, locals=0x7fd6abea3120, globals=0x7fd6abea3120, filename=<optimized out>, mod=<optimized out>) at Python/pythonrun.c:1025
#78 PyRun_StringFlags (str=0x7fd6abdbf4e8 "import requests; resp=requests.get('https://static.pddpic.com/assets/js/dba_a6f5600ee6b41a489053_1026.js'); print(resp.status_code)\n", start=257, globals=0x7fd6abea3120, locals=0x7fd6abea3120, flags=0x7fffc54f1f5c)
    at Python/pythonrun.c:949
#79 0x00005646aa66269b in PyRun_SimpleStringFlags (command=0x7fd6abdbf4e8 "import requests; resp=requests.get('https://static.pddpic.com/assets/js/dba_a6f5600ee6b41a489053_1026.js'); print(resp.status_code)\n", flags=flags@entry=0x7fffc54f1f5c) at Python/pythonrun.c:445
#80 0x00005646aa672f39 in run_command (cf=0x7fffc54f1f5c, command=0x5646ac07a1d0 L"import requests; resp=requests.get('https://static.pddpic.com/assets/js/dba_a6f5600ee6b41a489053_1026.js'); print(resp.status_code)\n") at Modules/main.c:301
#81 Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:748
#82 0x00005646aa65966c in main (argc=3, argv=<optimized out>) at ./Programs/python.c:69
(gdb) 
```
