### ISSUE TITLE
生成的.p12文件转换jks时提示密钥不正确

### ISSUE THREAD

**Issue by kidovin** [guanzhi/GmSSL#1285]
用gmssl生成.p12证书文件，使用jdk的keytool转换为.jks时提示密码不正确。
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at java.base/sun.security.tools.keytool.Main.loadSourceKeyStore(Main.java:2321)
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1233)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:415)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:408)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	... 7 more

**Comment by kidovin** [comment]
国密证书使用了自有的椭圆曲线，所以无法使用JDK自带的java.security解析证书，需要引入BouncyCastle，BC库支持国密算法。
参考文章：https://blog.csdn.net/qq_40806881/article/details/120524669?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-120524669-blog-123478181.pc_relevant_multi_platform_whitelistv3&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-120524669-blog-123478181.pc_relevant_multi_platform_whitelistv3&utm_relevant_index=1
