### ISSUE TITLE
使用3.0版本编译出来的libgmssl.a进行sm2加密后，结果使用java无法解密

### ISSUE THREAD

**Issue by itollei** [guanzhi/GmSSL#1350]
iOS端加密如下：
int sw_sm2_encrypt(const char *x, const char *y, unsigned char *plaintxt, unsigned char *ciphertxt, size_t *clen) {
    if (strlen(x) != 64 || strlen(y) != 64){
        return 0;
    }
    
    SM2_POINT pub_point;
    sm2_point_from_xy(&pub_point, (uint8_t *)x, (uint8_t *)y);
    SM2_KEY pub_key;
    sm2_key_set_public_key(&pub_key, &pub_point);
    
    size_t len;
    if (!sm2_encrypt(&pub_key, (uint8_t *)plaintxt, strlen((const char *)plaintxt), ciphertxt, &len)){
        return 0;
    }
    *clen = len;
    return 1;
}

java端解密报：
org.bouncycastle.crypto.InvalidCipherTextException: invalid cipher text
	at org.bouncycastle.crypto.engines.SM2Engine.decrypt(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.processBlock(Unknown Source)
	at org.zz.gmhelper.SM2Util.decrypt(SM2Util.java:144)
	at org.zz.gmhelper.test.SM2UtilTest.testEncryptAndDecrypt(SM2UtilTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by guanzhi** [comment]
是否可以给出完整可编译的Java代码？

**Comment by itollei** [comment]
老师，我使用的java代码在[https://github.com/itollei/gmhelper-master](url)上，您抽空帮我看下，问题出在哪里？非常感谢！

**Comment by voyager11** [comment]
> 老师，我使用的java代码在[https://github.com/itollei/gmhelper-master](url)上，您抽空帮我看下，问题出在哪里？非常感谢！

你好，你搞好了吗？我这边也是 他这个加密出来的密文HEX好奇怪，都是30开头的，应该是用什么格式或者加密过，请问怎么转回来？

**Comment by 596030631** [comment]
关于GMSSL-SM2与其他主流SM2算法加解密不通过的问题，这里有一个案例可以参考
- ## https://github.com/guanzhi/GmSSL/issues/1366#issuecomment-1320833842

**Comment by zhangq1005404376** [comment]
> > 老师，我使用的java代码在[https://github.com/itollei/gmhelper-master](url)上，你抽空帮我看下，问题出在哪里？非常感谢！>> 你好，你搞好了吗？我这边也是他这个加密出来的密文HEX好奇怪，都是30开头的，应该是用什么格式或加密过，请问怎么转回来？
30开头应该der编码的。理论上java那边应该是可以直接解这个格式

**Comment by Wang-GuangCheng** [comment]
[兼容.md](https://github.com/guanzhi/GmSSL/files/10389856/default.md)

**Comment by jiangyawei** [comment]
你好，有使用sm2给数据长度大于255的数据加密吗？非常感谢告知
